# Uncomment this line to define a global platform for your project
inhibit_all_warnings!
platform :ios, '7.0'
workspace 'ALADJumpDemo.xcworkspace'
source 'https://github.com/CocoaPods/Specs.git'


target 'ALADJumpDemo' do
pod 'SDWebImage', '~> 3.8.1'
xcodeproj 'ALADJumpDemo'
end
